name: Build Docker Image on macOS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Docker
        # macOS runners don't have Docker pre-installed, so we need to ensure it's available
        run: |
          # Check if Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Please ensure Docker Desktop is installed on your self-hosted runner."
            exit 1
          fi
          # Start Docker service if not running
          if ! docker info &> /dev/null; then
            echo "Starting Docker service..."
            open -a Docker
            # Wait for Docker to start
            echo "Waiting for Docker to start..."
            while ! docker info &> /dev/null; do
              sleep 5
            done
          fi
          echo "Docker is ready"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and tag Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: myapp:latest
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
      - name: Test Docker image
        run: |
          docker images
          echo "Running container to test..."
          docker run --rm myapp:latest echo "Container test successful"
