name: ibrahimadedayo/kub24
on:
  push:
    branches:
      - 'main'
      
env:
  IMAGE_NAME: nginx
  IMAGE_TAG: 1.27

jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ibrahimadedayo }}
          password: ${{ secrets.goodfellas2 }}
      -
        name: ibrahimadedayo/nginix:1:27
        uses: docker/build-push-action@v5
        with:
          context: devops-projects/docker_cicd_github_action/.
          push: false
          tags: ${{ secrets.ibrahimadedayo }}/${{ env.kub24 }}:${{ env.kub24 }}
