name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted  # Uses self-hosted runner

    container:
      image: ubuntu:latest  # Uses latest Ubuntu image
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y curl build-essential
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      
      - name: Build application
        run: |
          echo "Building application..."
          # Add your build commands here
      
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here
          
  docker:
    name: Build and Push Docker Image
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            yourusername/yourapp:latest
            yourusername/yourapp:${{ github.sha }}
          cache-from: type=registry,ref=yourusername/yourapp:buildcache
          cache-to: type=registry,ref=yourusername/yourapp:buildcache,mode=max
